// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

/*
Package test is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	Test
	Person
*/
package test

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FOO int32

const (
	FOO_X FOO = 17
)

var FOO_name = map[int32]string{
	17: "X",
}
var FOO_value = map[string]int32{
	"X": 17,
}

func (x FOO) Enum() *FOO {
	p := new(FOO)
	*p = x
	return p
}
func (x FOO) String() string {
	return proto.EnumName(FOO_name, int32(x))
}
func (x *FOO) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FOO_value, data, "FOO")
	if err != nil {
		return err
	}
	*x = FOO(value)
	return nil
}
func (FOO) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Person_PhoneType int32

const (
	Person_MOBILE Person_PhoneType = 0
	Person_HOME   Person_PhoneType = 1
	Person_WORK   Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}
var Person_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Person_PhoneType) Enum() *Person_PhoneType {
	p := new(Person_PhoneType)
	*p = x
	return p
}
func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}
func (x *Person_PhoneType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Person_PhoneType_value, data, "Person_PhoneType")
	if err != nil {
		return err
	}
	*x = Person_PhoneType(value)
	return nil
}
func (Person_PhoneType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Test struct {
	Label            *string             `protobuf:"bytes,1,req,name=label" json:"label,omitempty"`
	Type             *int32              `protobuf:"varint,2,opt,name=type,def=77" json:"type,omitempty"`
	Reps             []int64             `protobuf:"varint,3,rep,name=reps" json:"reps,omitempty"`
	Optionalgroup    *Test_OptionalGroup `protobuf:"group,4,opt,name=OptionalGroup,json=optionalgroup" json:"optionalgroup,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Test) Reset()                    { *m = Test{} }
func (m *Test) String() string            { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()               {}
func (*Test) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_Test_Type int32 = 77

func (m *Test) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func (m *Test) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_Test_Type
}

func (m *Test) GetReps() []int64 {
	if m != nil {
		return m.Reps
	}
	return nil
}

func (m *Test) GetOptionalgroup() *Test_OptionalGroup {
	if m != nil {
		return m.Optionalgroup
	}
	return nil
}

type Test_OptionalGroup struct {
	RequiredField    *string `protobuf:"bytes,5,req,name=RequiredField" json:"RequiredField,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Test_OptionalGroup) Reset()                    { *m = Test_OptionalGroup{} }
func (m *Test_OptionalGroup) String() string            { return proto.CompactTextString(m) }
func (*Test_OptionalGroup) ProtoMessage()               {}
func (*Test_OptionalGroup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Test_OptionalGroup) GetRequiredField() string {
	if m != nil && m.RequiredField != nil {
		return *m.RequiredField
	}
	return ""
}

type Person struct {
	Name             *string               `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Id               *int32                `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Email            *string               `protobuf:"bytes,3,req,name=email" json:"email,omitempty"`
	Phones           []*Person_PhoneNumber `protobuf:"bytes,4,rep,name=phones" json:"phones,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Person) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Person) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Person) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *Person) GetPhones() []*Person_PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

type Person_PhoneNumber struct {
	Number           *string           `protobuf:"bytes,1,req,name=number" json:"number,omitempty"`
	Type             *Person_PhoneType `protobuf:"varint,2,opt,name=type,enum=Person_PhoneType" json:"type,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Person_PhoneNumber) Reset()                    { *m = Person_PhoneNumber{} }
func (m *Person_PhoneNumber) String() string            { return proto.CompactTextString(m) }
func (*Person_PhoneNumber) ProtoMessage()               {}
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *Person_PhoneNumber) GetNumber() string {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return ""
}

func (m *Person_PhoneNumber) GetType() Person_PhoneType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Person_MOBILE
}

func init() {
	proto.RegisterType((*Test)(nil), "Test")
	proto.RegisterType((*Test_OptionalGroup)(nil), "Test.OptionalGroup")
	proto.RegisterType((*Person)(nil), "Person")
	proto.RegisterType((*Person_PhoneNumber)(nil), "Person.PhoneNumber")
	proto.RegisterEnum("FOO", FOO_name, FOO_value)
	proto.RegisterEnum("Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
}

func init() { proto.RegisterFile("test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x50, 0xcb, 0x4a, 0xf3, 0x50,
	0x10, 0xfe, 0xcf, 0xc9, 0x85, 0xbf, 0x53, 0x5b, 0xd2, 0xa9, 0x94, 0x43, 0x57, 0xa1, 0x28, 0x04,
	0x0b, 0x59, 0x14, 0xa4, 0xe8, 0x52, 0x68, 0x55, 0x6c, 0x4d, 0x39, 0x14, 0x74, 0x9b, 0x92, 0x41,
	0x03, 0x69, 0xce, 0x31, 0x97, 0x45, 0x5f, 0xcd, 0x47, 0xf2, 0x29, 0x24, 0x17, 0xa4, 0xd9, 0x7d,
	0x97, 0xe1, 0x9b, 0x6f, 0x06, 0xa0, 0xa0, 0xbc, 0xf0, 0x75, 0xa6, 0x0a, 0x35, 0xfb, 0x66, 0x60,
	0xee, 0x29, 0x2f, 0xf0, 0x12, 0xac, 0x24, 0x3c, 0x50, 0x22, 0x98, 0xcb, 0xbd, 0x9e, 0x6c, 0x08,
	0x4e, 0xc0, 0x2c, 0x4e, 0x9a, 0x04, 0x77, 0x99, 0x67, 0xdd, 0xf3, 0xe5, 0x52, 0xd6, 0x1c, 0x11,
	0xcc, 0x8c, 0x74, 0x2e, 0x0c, 0xd7, 0xf0, 0x0c, 0x59, 0x63, 0xbc, 0x83, 0x81, 0xd2, 0x45, 0xac,
	0xd2, 0x30, 0xf9, 0xc8, 0x54, 0xa9, 0x85, 0xe9, 0x32, 0x0f, 0x16, 0x63, 0xbf, 0xca, 0xf7, 0x83,
	0xd6, 0x7a, 0xac, 0x2c, 0xd9, 0x9d, 0x9c, 0xde, 0xc2, 0xa0, 0xe3, 0xe3, 0x15, 0x0c, 0x24, 0x7d,
	0x95, 0x71, 0x46, 0xd1, 0x3a, 0xa6, 0x24, 0x12, 0x56, 0xdd, 0xaa, 0x2b, 0xce, 0x7e, 0x18, 0xd8,
	0x3b, 0xca, 0x72, 0x95, 0x56, 0x85, 0xd2, 0xf0, 0x48, 0x6d, 0xfb, 0x1a, 0xe3, 0x10, 0x78, 0x1c,
	0x09, 0xee, 0x72, 0xcf, 0x92, 0x3c, 0x8e, 0xaa, 0x13, 0xe9, 0x18, 0xc6, 0x89, 0x30, 0x9a, 0x13,
	0x6b, 0x82, 0x73, 0xb0, 0xf5, 0xa7, 0x4a, 0x29, 0x17, 0xa6, 0x6b, 0x78, 0xfd, 0xc5, 0xd8, 0x6f,
	0x22, 0xfd, 0x5d, 0xa5, 0xbe, 0x96, 0xc7, 0x03, 0x65, 0xb2, 0x1d, 0x99, 0x6e, 0xa0, 0x7f, 0x26,
	0xe3, 0x04, 0xec, 0xb4, 0x46, 0xed, 0xde, 0x96, 0xe1, 0xf5, 0xd9, 0xdb, 0x86, 0x8b, 0x51, 0x27,
	0x71, 0x7f, 0xd2, 0xd4, 0x7c, 0x71, 0x36, 0x87, 0xde, 0x9f, 0x84, 0x00, 0xf6, 0x36, 0x78, 0x78,
	0xde, 0xac, 0x9c, 0x7f, 0xf8, 0x1f, 0xcc, 0xa7, 0x60, 0xbb, 0x72, 0x58, 0x85, 0xde, 0x02, 0xf9,
	0xe2, 0xf0, 0x9b, 0x0b, 0x30, 0xd6, 0x41, 0x80, 0x16, 0xb0, 0x77, 0x67, 0xf4, 0x1b, 0x00, 0x00,
	0xff, 0xff, 0x26, 0x00, 0xf9, 0xbb, 0xc4, 0x01, 0x00, 0x00,
}
